Replace tabs with spaces.

diff --git a/bin/papers-db b/bin/papers-db
--- a/bin/papers-db
+++ b/bin/papers-db
@@ -13,60 +13,60 @@ source "$LOCAL_DIR/papers_db.sh"
 
 case "$1" in
     "init")
-	init
-	;;
+    init
+    ;;
     "all")
-	all_papers
-	;;
+    all_papers
+    ;;
     "add")
-	shift
-	paper="$1"
-	add "$paper"
-	shift
-	for tag in "$@"; do
-	    tag_add "$paper" "$tag"
-	done
-	;;
+    shift
+    paper="$1"
+    add "$paper"
+    shift
+    for tag in "$@"; do
+        tag_add "$paper" "$tag"
+    done
+    ;;
     "add-from-url")
-	shift
-	tmpdir=$(mktemp -d papers_db.XXXXXXXXXX)
-	pushd "$tmpdir"
-	wget "$1"
-	fname="$(ls)"
-	popd
-	if [ -f "$tmpdir/$fname" ]; then
-	    mkdir -p Papers
-	    mv "$tmpdir/$fname" "Papers/$fname"
-	    add "Papers/$fname"
-	    shift
-	    for tag in "$@"; do
-		tag_add "Papers/$fname" "$tag"
-	    done
-	else
-	    echo "Failed to download"
-	    exit 1
-	fi
-	rm -rf "$tmpdir"
-	;;
+    shift
+    tmpdir=$(mktemp -d papers_db.XXXXXXXXXX)
+    pushd "$tmpdir"
+    wget "$1"
+    fname="$(ls)"
+    popd
+    if [ -f "$tmpdir/$fname" ]; then
+        mkdir -p Papers
+        mv "$tmpdir/$fname" "Papers/$fname"
+        add "Papers/$fname"
+        shift
+        for tag in "$@"; do
+        tag_add "Papers/$fname" "$tag"
+        done
+    else
+        echo "Failed to download"
+        exit 1
+    fi
+    rm -rf "$tmpdir"
+    ;;
     "tag-show")
-	tag_show "$2"
-	;;
+    tag_show "$2"
+    ;;
     "tag-search")
-	shift
-	tag_search "$#" "$@"
-	;;
+    shift
+    tag_search "$#" "$@"
+    ;;
     "tag-all")
-	tag_all
-	;;
+    tag_all
+    ;;
     "tag-add")
-	shift
-	paper="$1"
-	shift
-	for tag in "$@"; do
-	    tag_add "$paper" "$tag"
-	done
-	;;
+    shift
+    paper="$1"
+    shift
+    for tag in "$@"; do
+        tag_add "$paper" "$tag"
+    done
+    ;;
     *)
-	echo "Unknown command: $1"
-	exit 1
+    echo "Unknown command: $1"
+    exit 1
 esac
